spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode:never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  social-login:
    provider:
      apple:
        redirect-uri: https://lttakkeun.app.com/apple/callback/
        grant-type: authorization_code
        client-id: ttakkeun.app.com
        key-id: 4FHKZ8T3JS
        team-id: 8B8B4462NV
        audience: https://appleid.apple.com
        private-key: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPQGPRZ9oIGAb6vrac5qBDEedIMdWGC5XoQ2vA9lEv9OgCgYIKoZIzj0DAQehRANCAAS/SY9RpfX94Ok3ZyDGK0FLQbU/eM9k87x3FsD7evBxGLZuF+eyVFSJedGDq7jifLEQiaV0tRkhZdVoF3CzBPNE
jwt:
  secretKey: stressstressstresstresstresstressstressstressstressstressstressstress

server:
  port: 8080
